cello_app/config/routes.rb
Rails.application.routes.draw do

  get 'lists/new_todo' => 'todos#new'

  resources :todos
  resources :lists


  root "lists#index"

end

cello_app/app/models/list.rb
class List < ActiveRecord::Base
  has_many :todos
end

cello_app/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :list
end

cello_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cello_app/app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @todos = @list.todos
  end

  def new
    @list = List.new
  end

  def create
  @list = List.new
  @list.name = params["list"]["name"]
  @list.save

    redirect_to '/lists'
  end
end

cello_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
    @list =  List.find(params[:list])

  end

  def create
    @todo = Todo.new
    @todo.item = params["todo"]["item"]
    @todo.list_id = params["todo"]["list_id"]

    @todo.save

    redirect_to @todo.list
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to '/lists'
  end


end

cello_app/app/helpers/application_helper.rb
module ApplicationHelper
end

cello_app/app/helpers/lists_helper.rb
module ListsHelper
end

cello_app/app/helpers/todos_helper.rb
module TodosHelper
end

cello_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CelloApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/paper/bootstrap.min.css">


</head>
<body>
  <header id="header">
    <h1><%= link_to "Cello", '/' %></h1>
    <h4>The ToDo List for Musicians</h4>
    <%= link_to '<button type="button" class="btn btn-primary btn-lg">Create New List</button>'.html_safe, '/lists/new' %>
  </header><!-- /header -->
  <section class="main">
    <div class="yields">
      <%= yield %>
    </div>
  </section>

</body>
</html>

cello_app/app/views/lists/_form.html.erb
<%= form_for @list do |f|%>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
<%= f.submit "New List", :class => 'btn btn-primary btn-sm' %>
<% end %>

cello_app/app/views/lists/index.html.erb
<h2>Your Lists</h2>
<ul>
<% @lists.each do |list| %>
<li><%= link_to list.name, list %></li>
<% end %>
</ul>

<%= link_to '<button type="button" class="btn btn-primary btn-sm">Create New List</button>'.html_safe, '/lists/new' %>

cello_app/app/views/lists/new.html.erb
<h2>Make a New List</h2>
<%= render 'form' %>

cello_app/app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<ul>
  <% @todos.each do |todo| %>
    <li><%= link_to todo.item, todo %></li>
  <% end %>

</ul>


<%= link_to '<button type="button" class="btn btn-primary btn-sm">Add New To-Do List item</button>'.html_safe, new_todo_path(:list => @list.id) %><br><br>
<%= link_to '<button type="button" class="btn btn-danger btn-sm">Delete List</button>'.html_safe, @list, method: :delete, data: { confirm: 'Are you sure?' } %>

cello_app/app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :item %><br>
  <%= f.text_field :item %><br>
  <%= f.hidden_field :list_id, :value => @list.id%><br>
  <%= f.submit "New To Do", :class => 'btn btn-primary btn-xs' %>
<% end %>

cello_app/app/views/todos/new.html.erb
<h2>Add to your list</h2>
<%= render 'form' %>

cello_app/app/views/todos/show.html.erb
<h2><%= @todo.item %></h2>



<%= link_to '<button type="button" class="btn btn-success btn-sm">Complete</button>'.html_safe, @todo, method: :delete, data: { confirm: 'Are you sure?' } %>